### ISSUE TITLE
trouble with css

### ISSUE THREAD

**Issue by cybermerlin** [apache/incubator-weex-cli#440]
weex latest
weex create lololo

```css
.tool-bar a.list-icon {
  	background-image: url( "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyBpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNSBXaW5kb3dzIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkYzNkFCQ0ZBMTBCRTExRTM5NDk4RDFEM0E5RkQ1NEZCIiB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOkYzNkFCQ0ZCMTBCRTExRTM5NDk4RDFEM0E5RkQ1NEZCIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6RjM2QUJDRjgxMEJFMTFFMzk0OThEMUQzQTlGRDU0RkIiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6RjM2QUJDRjkxMEJFMTFFMzk0OThEMUQzQTlGRDU0RkIiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz7h1bLqAAAAWUlEQVR42mL8////BwYGBn4GCACxBRlIAIxAA/4jaXoPEkMyjJ+A/g9MDJQBRhYg8RFqMwg8RJIUINYLFDmBUi+ADQAF1n8ofk9yIAy6WPg4GgtDMRYAAgwAdLYwLAoIwPgAAAAASUVORK5CYII=" );
}
```
```bash
./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"13935","vue":true,"scoped":false,"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./raw/bbfbd1608d5a3251cde5d8a80ad565c7/App.vue Module build failed: TypeError: unitsToPx[unit] is not a function at /usr/src/app/node_modules/postcss-plugin-weex/src/index.js:29:35 at String.replace (<anonymous>) at rule.walkDecls.decl (/usr/src/app/node_modules/postcss-plugin-weex/src/index.js:28:30) at /usr/src/app/node_modules/postcss/lib/container.js:188:28 at /usr/src/app/node_modules/postcss/lib/container.js:144:26 at Rule.each (/usr/src/app/node_modules/postcss/lib/container.js:110:22) at Rule.walk (/usr/src/app/node_modules/postcss/lib/container.js:143:21) at Rule.walkDecls (/usr/src/app/node_modules/postcss/lib/container.js:186:25) at root.walkRules.rule (/usr/src/app/node_modules/postcss-plugin-weex/src/index.js:22:12) at /usr/src/app/node_modules/postcss/lib/container.js:237:28 at /usr/src/app/node_modules/postcss/lib/container.js:144:26 at Root.each (/usr/src/app/node_modules/postcss/lib/container.js:110:22) at Root.walk (/usr/src/app/node_modules/postcss/lib/container.js:143:21) at Root.walkRules (/usr/src/app/node_modules/postcss/lib/container.js:235:25) at /usr/src/app/node_modules/postcss-plugin-weex/src/index.js:20:10 at LazyResult.run (/usr/src/app/node_modules/postcss/lib/lazy-result.js:277:20) at LazyResult.asyncTick (/usr/src/app/node_modules/postcss/lib/lazy-result.js:192:32) at LazyResult.asyncTick (/usr/src/app/node_modules/postcss/lib/lazy-result.js:204:22) at LazyResult.asyncTick (/usr/src/app/node_modules/postcss/lib/lazy-result.js:204:22) at processing.Promise.then._this2.processed (/usr/src/app/node_modules/postcss/lib/lazy-result.js:231:20) at new Promise (<anonymous>) at LazyResult.async (/usr/src/app/node_modules/postcss/lib/lazy-result.js:228:27) at LazyResult.then (/usr/src/app/node_modules/postcss/lib/lazy-result.js:134:21) at loadPostcssConfig.then.config (/usr/src/app/node_modules/vue-loader/lib/style-compiler/index.js:42:10) at <anonymous> @ ./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"13935","vue":true,"scoped":false,"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./raw/bbfbd1608d5a3251cde5d8a80ad565c7/App.vue 4:14-275 @ ./raw/bbfbd1608d5a3251cde5d8a80ad565c7/App.vue @ ./raw/bbfbd1608d5a3251cde5d8a80ad565c7/web.entry.js
```
